### ISSUE TITLE
cant add conditions or actions

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/rules#1]
a few things i thought might help (because they caused immediate php errors): 
- WHATEVER->language should be changed to WHATEVER->langcode everywhere. 
- in ui.theme.inc on line 186 you find misc/collapse, should be core/misc/collapse

but in the end still didnt help since whatever function builds the data selectors doesnt seem to be returning any, so the list in the fieldset isnt being populated, and as well the autocomplete doesnt work.

**Comment by Graham-72** [comment]
Thanks @docwilmot for trying it and reporting these issues.  I find I can add conditions and actions so it must depend on circumstances. But of course we need it to be 100% reliable. I will do some more checking.

**Comment by docwilmot** [comment]
also get
`( ! ) Fatal error: Call to undefined function entity_crud_get_info() in C:\wamp\www\backdrop\backdrop\modules\rules\rules.module on line 1184`
on trying to run updates
i had updated to the latest backdrop and token and was trying to update. (is token no longer required? does your version work without it?)

**Comment by docwilmot** [comment]
incidentally i can add conditions with entity as selector (eg node) but not entity properties (eg node:author:name)

**Comment by docwilmot** [comment]
In D7
![d7rules](https://cloud.githubusercontent.com/assets/1042283/6656952/d76773f2-cb08-11e4-9065-56767f1b3e74.PNG)

In BD
![bdrules](https://cloud.githubusercontent.com/assets/1042283/6656957/282f061a-cb09-11e4-89c4-1cc750f6b9ff.PNG)

**Comment by Graham-72** [comment]
I think this is fixed. Please re-open if not.
