### ISSUE TITLE
missing entity_load_single() function

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/rules#10]
last commit (https://github.com/backdrop-contrib/rules/commit/5c87a99fad69e2dfa744e07294c3ed963f264a37) brakes rules (and ubercart port) because of entity_load_single() missing function.

**Comment by herbdool** [comment]
You probably want to just use the entity_load() function in core which loads a single entity. https://github.com/backdrop/backdrop/blob/1.x/core/modules/entity/entity.module

**Comment by robertgarrigos** [comment]
Thanks @herbdool I'll do that
