### ISSUE TITLE
Built-in path cleaning settings are inaccessible

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#100]
On the Rules settings page at admin/config/workflow/rules/settings, one of the options for "URL path cleaning method" is "Rules (built in)". Details of its behavior are determined by four variables stored in config in rules.settings.json:

* `rules_path_replacement_char`
* `rules_path_lower_case`
* `rules_clean_path`
* `rules_path_transliteration`

None of these are accessible if a user wanted to edit them. If they're intended to be uneditable, then they should be defined as constants in the code; if they're intended to be editable, there needs to be a way to edit them. For example, if the select is set to "Rules (built in)", then additional edit fields become visible that can then be changed.

Incidentally, `rules_admin_settings()` (where these settings should go) currently contains the conditional `if (module_exists('path'))...`. But since `path` module is now in core, this will always evaluate to TRUE and so the conditional can be removed.

**Comment by bugfolder** [comment]
OK, this is pretty weird. Even in the D7 version of Rules, there was no way to set the variable `rules_clean_path`. And indeed, in a fresh install of D7 Rules, it's never set. Its only reference is this line in `rules_path_default_cleaning_method()`:

```
    $array = variable_get('rules_clean_path', array('/[^a-zA-Z0-9\-_]+/', $replace));
```

So in every such call, `$array` is initialized with the default value `array('/[^a-zA-Z0-9\-_]+/', $replace)`. The first element is a regex that gets passed to `preg_replace()`. The second is the replacement character (which is also stored as a config variable).

There's absolutely no reason to store that entire array as a config variable, since its second element is already stored as a separate config variable. All that should be stored is the regex itself. (I can't think of any good reason why it needs to ever change, but it looks like Rules was originally built to allow that possibility.)

So...I think the best solution for that particular variable is to just completely deprecate `rules_clean_path` as a config variable. The only way it was ever stored in the D7 variables table was if some other module altered it directly.

Instead, we should introduce a new config variable that is just the regex, which I will suggest we call `rules_path_regex` (for naming consistency with the other three settings variables, see above), and then set its value to the current default value of the regex upon initialization and/or upgrade. And then, going forward, people can alter it if they want.

Incidentally, this whole issue seems like it's a corner case of a corner case. Since Path module is now in core, it's always present, and the logical value of the Rules setting would be to use the path cleaning method provided by Path module. There's no more need for Rules to have a built-in method. But since it's already present, and upgraders may very well have used the built-in method, I guess we should keep supporting it.

**Comment by laryn** [comment]
Maybe we could mark that edge case functionality as deprecated and plan to remove it at some point?

**Comment by bugfolder** [comment]
How about if we detect the array during upgrade/update, and if it IS present, convert it to the new cleaner way of handling? We still have to fix the settings to make them settable (which I'm working on now).

**Comment by bugfolder** [comment]
I also see residue of references to `ctools` and `pathauto` modules and functions. CTools is not needed in Backdrop; Pathauto's functionality is incorporated into Path module. So this issue would also be a good place to clean up that cruft.

**Comment by bugfolder** [comment]
There's also a bit of CTools-related cruft in the module (function `rules_path_clean_ctools()`). This would be a good opportunity to clean that out.

**Comment by laryn** [comment]
👍👍

**Comment by laryn** [comment]
> the logical value of the Rules setting would be to use the path cleaning method provided by Path module. There's no more need for Rules to have a built-in method. But since it's already present, and upgraders may very well have used the built-in method, I guess we should keep supporting it

@bugfolder I took this to mean that we should consider `rules_path_default_cleaning_method` as a deprecated (but currently still supported) option, and default to use `rules_path_clean_path` as the default option in new installs. Is that accurate? (If so, changing the default value in the `.json` and renaming the value in question as `rules_path_deprecated_cleaning_method` might be in order).

**Comment by bugfolder** [comment]
I hadn't considered changing the default, but yes, that makes total sense.

Should the deprecation be made more prominent, e.g., by saying something about it in the UI?

**Comment by laryn** [comment]
Yes, that might be a good idea! `Rules (built in)` could just become `Rules (deprecated)`?

**Comment by bugfolder** [comment]
How about: `Rules (built-in, deprecated)`?

I'll update the PR.

**Comment by laryn** [comment]
@bugfolder One more thought -- do you think we should add a `watchdog_deprecated_function` call to `rules_path_default_cleaning_method()`?

**Comment by bugfolder** [comment]
Functionally, that makes sense. The actual watchdog message that gets posted is `The function @original_caller (@file:@line) called deprecated function @function(). It will be removed in the next major release of Backdrop.`. That's not necessarily the case for a contrib module, but then I guess we could make that the plan.

**Comment by laryn** [comment]
I guess I don't have super strong feelings on it but if we don't make a plan it might stay deprecated but supported forever?

**Comment by bugfolder** [comment]
No strong feelings here, either. BD2.0 seems like far enough out that removing it then would be justified. One more PR update to come.
