### ISSUE TITLE
Rename Rules tokens to be clearer, grouped in token browser

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#103]
Currently, the Rules tokens have fairly generic human-readable names (e.g., `date`, `integer`, `text`, etc.) that results in some poor ergonomics in the Token browser:

* Rules tokens are scattered throughout the browser, instead of being grouped together
* The generic names are lower-case, but the standard for human-readable names appears to be capitalized
* The generic names suggest they have wider utility, when in fact they are specific to usage within Rules.

See this image of the Token browser, with Rules tokens highlighted.

![token browser](https://user-images.githubusercontent.com/29214084/141656078-1e63bd25-5b92-40a6-9563-dcf76ffc8657.jpg)

The proposal is to rework `rules_token_info()` so that the tokens are (a) grouped, (b) have human-readable names that indicate their specificity to Rules, so that they don't clutter up the Token browser when not needed.

Note that I'm _not_ proposing changing the tokens themselves—all existing tokens will work exactly the same—just changing the human-readable names to improve the Token browser experience.

**Comment by bugfolder** [comment]
Turns out they can't be put into a single collapsible group because each has a unique needs-data type, but we can at least group them in the browser (with a 1-line change, so unlikely to have other side effects). Here's the result of the PR.

![token browser](https://user-images.githubusercontent.com/29214084/141662561-a47fac42-1ed2-4b2e-b3c9-658e9fe7711f.jpg)

**Comment by laryn** [comment]
Good UX improvement, thanks!
