### ISSUE TITLE
Undefined $property in rules_config_load_multiple()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#110]
Running the Ubercart tests reveals a problem in the Rules function `rules_config_load_multiple()`, which is

> Undefined variable `$property` in `rules_config_load_multiple()` line 920

And indeed, the variable `$property` is undefined when it is used to get the keys for the return array.

A closer examination of this function reveals several issues. Beginning with the return value, which is documented in the docblock as

> An array of rule configurations indexed by their ids.

However, examination of the several places that `rules_config_load_multiple()` is called shows that other functions expect it to be keyed on the `name`, not the `id` of the entity. So the docblock should be corrected.

But then there's a bunch of unnecessary checking, because the `entity_keys` of the `rules_config` entity always contains the `name` key; we don't need to check for its existence.

So the overall function can be streamlined, and the undefined variable `$property` goes away.

With the changes in the attached PR, the formerly failing Ubercart tests run without error. (Some Ubercart tests still fail for unrelated reasons.)

**Comment by argiepiano** [comment]
After our discussion with @bugfolder  on Zulip, I have a separate PR (#118) that fixes this issue and takes care of additional important details. See a mention of those details in #117
