### ISSUE TITLE
Rules tests failing

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#114]
Several of the Rules tests currently fail when run from the UI. Listing passing (checked) and failing (unchecked) here (in the order they appear on the testing page); will add to the PR until they're all checked off.

- [x] Reaction rules (RulesTriggerTestCase)
- [ ] Rules core integration (RulesIntegrationTestCase)
- [x] Rules data tests (RulesTestDataCase)
- [x] Rules engine tests (RulesTestCase)
- [x] Rules event dispatchers (RulesEventDispatcherTestCase)
- [x] Rules invocation enabled (RulesInvocationEnabledTestCase)
- [x] Rules scheduler tests (RulesSchedulerTestCase)
- [x] Rules UI minimal profile tests (RulesAdminMinimalProfileTestCase)
- [x] Rules UI tests (RulesUiTestCase)

**Comment by bugfolder** [comment]
Applied PR https://github.com/backdrop-contrib/rules/pull/125, which fixes some of the tests, but reopening this issue because there's still some tests to be fixed.

**Comment by argiepiano** [comment]
I've added a final PR - #137 - which fixes the failing tests in RulesIntegrationTestCase. 

Important: to test this locally with the UI, Entity Tokens v. 2 must be present in the modules folder. 

I believe these are the last tests needing fixing. These tests will fail if the following PRs are not applied first:

- #129 
- #130 
- #135 
- #136

**Comment by bugfolder** [comment]
Merged all the PRs, which fixes most tests (yay, awesome work!). Reopening because there remains one failing test in `RulesIntegrationTestCase->testUserIntegration()`.

**Comment by bugfolder** [comment]
All tests passing now!
