### ISSUE TITLE
Class 'EntityDefaultFeaturesController' not found

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/rules#13]
I'm having this error running rules with ubercart: 

```
Fatal error: Class 'EntityDefaultFeaturesController' not found in /app/modules/rules/rules.features.inc on line 13
```
I guess this is related to last two commits in rules. (5c87a99fad69e2dfa744e07294c3ed963f264a37 and a4f84c9d4b79c19b558bcfc792b373da06e6c96a)

**Comment by herbdool** [comment]
You probably don't need Feature-related functionality in this module.

**Comment by robertgarrigos** [comment]
in fact, rules.features.inc calls that class. We might need, then, delete that file.

**Comment by herbdool** [comment]
Yes, the features functionality in Rules should be removed at this point since there is no Features module in Backdrop and it would work completely differently. And it also means remove references to the classes in rules_autoload_info() in rules.module as well.

**Comment by robertgarrigos** [comment]
great. I'll do that and post a PR
