### ISSUE TITLE
Add dependency on Entity Tokens module

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#143]
As discussed in a private Zulip discussion with @argiepiano, many tokens are not available to Rules in the "Direct input" boxes, e.g., [site:current_user:mail], or more detailed field tokens like [node:field_tags:0:name]. These will appear if the Entity Tokens module is enabled. Entity Tokens module is also required for all of the automated tests to run.

So, we should add Entity Tokens (>= 2.0.0) as a dependency for Rules module. This would require some additional changes to support:

* Note the dependency in the .info file and add some explanation in the README
* Since this is an API change, bump the minor version number (not a bugfix release)
* Like Entity Plus and Entity UI, this is a moduled required by Backdrop Rules that does not exist in Drupal 7, so would require a Drupal stub module (or automatic enablement during migration) for those migrating from Drupal 7.

**Comment by argiepiano** [comment]
Thanks, @bugfolder . Unlike Entity Plus or Entity UI, Entity Tokens DID exist as a module in D7. It was part of the Entity API module, but it could be enabled/disabled separately. So you will not need a stub module, I believe.

**Comment by bugfolder** [comment]
Ah, thanks for clarifying!
