### ISSUE TITLE
When adding actions with the UI, the latest action doesn't appear at the bottom of the list

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/rules#147]
## Description of the bug
When adding new actions to a Rule with the UI, the latest addition doesn't appear at the bottom of the list. Rather, it's always second in the list, meaning that you have to manually drag it down.

## How to reproduce
Add an action to  Rule through the UI.

## Expected behavior
The latest added action should be at the bottom of the list.

## Actual behavior
The added action appear second in the list.

**Comment by argiepiano** [comment]
Upon further testing, this issue is only present in PHP 7.4. Earlier PHP versions correctly places the last action at the bottom of the list. Further digging needed.

**Comment by argiepiano** [comment]
The issue is in [line 357](https://github.com/backdrop-contrib/rules/blob/7319afaf37fcc97489d46edc92e58b7deae9e5a2/ui/ui.forms.inc#L357) in ui.forms.inc. While the method `end()` worked in 7.3 and earlier, it is not supported for classes that extend ArrayIterator. 

A possible fix is to do `$iterator[count($iterator)-1];` to get the last element. This is suggested in[ postings in StackExchange](https://stackoverflow.com/questions/60339183/arrayobject-does-not-work-with-end-in-php-7-4) for a similar class (ArrayObject) which also implements Iterator.

This fix needs to be done also to `rules_ui_add_element()` in the same file. 

PR coming.

**Comment by argiepiano** [comment]
PR #152

**Comment by bugfolder** [comment]
This looks related to the first item in https://github.com/backdrop-contrib/rules/issues/107, addressed by the D7 patch on https://www.drupal.org/node/3250516.

**Comment by argiepiano** [comment]
Yes. I think the solution there is more idiomatic than what I proposed in my PR. I'll change to that.

**Comment by argiepiano** [comment]
Duplicate of #107.
