### ISSUE TITLE
Backdrop's filter_entity_insert() expects EntityInterface but Rules doesn't use it

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/rules#16]
I'm creating this as a separate issue:

> Error: Cannot instantiate abstract class Entity in EntityDatabaseStorageController->create() (line 473 of /app/core/modules/entity/entity.controller.inc).

@docwilmot did some detective work https://github.com/backdrop-contrib/rules/issues/3#issuecomment-264767625:

> Whats happening here is that Rules is creating a new instance of RulesReactionRule which is not an extension of Entity but the controller is EntityAPIControllerExportable from Entity API (or at least the "extentity" code duplicated in the port).
>
> So eventually when DefaultEntityController::save() is called to save the new object, it invokes the entity_insert() hooks, passing the RulesReactionRule object. But when filter_entity_insert(EntityInterface $entity) runs, it requires and expects an EntityInterface object, not a RulesReactionRule because we've decided to do strict typing.
>
> And things go sour.
>
> This doesnt cause problems elsewhere because all core calls to DefaultEntityController::save() are passed real entities.

**Comment by Graham-72** [comment]
I'm thinking this is no longer an issue. Please re-open if necessary.
