### ISSUE TITLE
Rules_i18n submodule for translation of rules

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/rules#167]
This is a companion issue to https://github.com/backdrop-contrib/entity_plus/issues/67 to try to get the `rules_i18n` submodule functional.

**Comment by argiepiano** [comment]
Thanks, @laryn . I'll take a look soon. 
PR #168

**Comment by bugfolder** [comment]
Note that automated tests have been (hopefully temporarily) disabled by https://github.com/backdrop-contrib/rules/pull/190.

**Comment by argiepiano** [comment]
Hi @laryn and @bugfolder. I've done work on this and the related Entity Plus issues for translation. I got the module and tests working in my local now. I will submit a PR here, BUT it will fail (for now) as we need the following changes to be merged first:

- https://github.com/backdrop-contrib/entity_plus/issues/67
- https://github.com/backdrop-contrib/entity_plus/issues/144
- https://github.com/backdrop-contrib/entity_plus/issues/146

If any of you has the time to review those 3, that would speed things up! (@laryn already looked at 144)

**Comment by argiepiano** [comment]
PR https://github.com/backdrop-contrib/rules/pull/193 submitted.

Tests will fail, as they need to E+ issues merged first, but I wanted to submit before moving on to other issues.

**Comment by bugfolder** [comment]
I think either #193 will need to be rebased, or else there will need to be a follow-up to undo the disabling of the tests that happened in the (already merged) #190.

**Comment by argiepiano** [comment]
I thought I was working from the current dev version. In fact you can see this PR undoing #190. Did I misunderstand?

<img width="828" alt="Screen Shot 2023-01-07 at 6 01 19 PM" src="https://user-images.githubusercontent.com/9938978/211176055-3d3dc345-720f-40eb-ac2b-180e60142c5a.png">

**Comment by bugfolder** [comment]
No, I'm just blind. No worries.

**Comment by bugfolder** [comment]
Looks like https://github.com/backdrop-contrib/rules/pull/168 should be closed.

I think this is RTBC, but I'm marking it MRR so that it waits on the E+ issues to be merged (per @argiepiano's comment above).

**Comment by argiepiano** [comment]
Yes, #168  should be closed now that we have the other PR.

**Comment by bugfolder** [comment]
I see that the three E+ issues have been closed and E+ did a new release 3 weeks ago. So I think that was what was blocking, and this should now be RTBC.

**Comment by argiepiano** [comment]
Yes, it should be good to go
