### ISSUE TITLE
Update GHA configuration

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/rules#173]
Seems best to follow @indigoxela's lead on GHA configuration, so we should update to match this latest:

 - https://github.com/backdrop-contrib/i18n/commit/9067c22d665be882c8f06bea88af2f5aa88dee01

**Comment by bugfolder** [comment]
Most of that is Greek to me, but we definitely shouldn't be sending telemetry data. So, makes sense.

**Comment by bugfolder** [comment]
@Laryn, since this only affects GHA and telemetry, there's no way to test it purely locally. Is the only way to test it to do a release to trigger the action? (And then can we verify whether it did what it was supposed to?)

**Comment by laryn** [comment]
I think you are right.

**Comment by bugfolder** [comment]
@laryn, @argiepiano, since @yorkshire-pudding was asking about a release (https://github.com/backdrop-contrib/rules/issues/176), how about if we merge this, do a new bugfix release to test it, and then we can do another bugfix release after further issues get addressed?

**Comment by laryn** [comment]
Sounds like a plan! Do you want to merge/make the release or should I?

**Comment by argiepiano** [comment]
Agreed. What would you like to do with #138? If the PRs for core issue [5499](https://github.com/backdrop/backdrop-issues/issues/5499) gets merged, then #138 is not needed.

**Comment by bugfolder** [comment]
@laryn, I'll do the merge and release.

@argiepiano, we'll leave 138 on hold until 5499 is merged in, then I'll close it unmerged. I had a code request on PR https://github.com/backdrop-contrib/rules/pull/171; if you're OK with it (and merge it into the PR), then I'll include that one as well.

**Comment by argiepiano** [comment]
@bugfolder, I committed your suggestions in #171

**Comment by bugfolder** [comment]
I did the release. When  I auto-generated the release notes, I realized there are a TON of changes (lots of great @argiepiano PRs!), but also, new added requirements (e.g., Entity Tokens). So I bumped the minor version number (versus a mere bugfix release) and added notes about the new requirements to the release notes.

@laryn, can you check to see if the GHA fix did its thing properly?

**Comment by laryn** [comment]
It's largely working but I found a typo that I made. Doh!

**Comment by laryn** [comment]
I made a new PR here that fixes the typo. 
https://github.com/backdrop-contrib/rules/pull/177

**Comment by bugfolder** [comment]
Merged. I'll make a new bugfix release.

**Comment by laryn** [comment]
I don't know that this would have any effect on the release -- maybe no need? @bugfolder

**Comment by bugfolder** [comment]
Ah well, too late.

**Comment by laryn** [comment]
No worries. 😄

**Comment by laryn** [comment]
Tested and now we get the pretty green colors:

![Screen Shot 2022-03-07 at 2 39 30 PM](https://user-images.githubusercontent.com/871421/157114251-e72a8130-b173-4f56-97da-f715e8f6162a.jpg)
