### ISSUE TITLE
Next expected release? Dependency on Entity_token

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/rules#176]
I've ported a module - [Rules Throttle](https://github.com/backdrop-contrib/rules_throttle) that needs entity_token to return values from it so I've added as a dependency.  However, I note that Rules has added entity_token as a dependency since the last release.

As Rules will require this module, then going forward there should be no need to have the dependency explicitly listed in that module.  When do you expect to do the next release of Rules?

**Comment by argiepiano** [comment]
@yorkshire-pudding I came onboard Rules recently. @bugfolder has been the "chief maintainer" - it's up to him when the new release will be done. I think we have a few ongoing issues that would be good to resolve before the next release.

**Comment by yorkshire-pudding** [comment]
Thanks @laryn @argiepiano @bugfolder - I'll remove the entity_token direct dependency from rules_throttle and get it released.
