### ISSUE TITLE
Operations for "Loop" elements do not include "Add action" and "Add loop"

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/rules#179]
When you create a loop, Backdrop Rules does not show the operations "Add action" or "Add loop" for the new loop, like the D7 counterpart. See snapshots

Drupal
<img width="1254" alt="Screen Shot 2022-05-22 at 5 26 20 PM" src="https://user-images.githubusercontent.com/9938978/169720676-498af083-b26d-435e-86f3-fbe4b3a8308d.png">

Backdrop 
<img width="1225" alt="Screen Shot 2022-05-22 at 5 26 32 PM" src="https://user-images.githubusercontent.com/9938978/169720679-2b0e0208-ba83-44ad-ad2b-c9f77cbe8d00.png">

**Comment by argiepiano** [comment]
I've found the issue. When #105 was fixed, the additional operations 'Add action' and 'Add loop' were merged into the wrong array element for the render array. 

PR #180

**Comment by bugfolder** [comment]
Tested, it works. Thanks, @argiepiano! Merged.
