### ISSUE TITLE
Data selection drop-down issues

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/rules#184]
It seems that the data selection drop-down could use some better styling. It currently looks like this:

![image](https://user-images.githubusercontent.com/2385329/178184825-8ca71ea6-1383-4215-9be9-a15c06f915b7.png)

Suggestions:
- Fix line-height/padding of drop-down items
- Make arrow button on right side match height/style of field

Perhaps something like this:

![image](https://user-images.githubusercontent.com/2385329/178185354-ecdce4ac-a2a3-411a-928d-663a864260bd.png)

**Comment by argiepiano** [comment]
Thanks @BWPanda. Will you be able to provide a PR?

**Comment by ghost** [comment]
Not sure how to make this work for all themes...

**Comment by bugfolder** [comment]
I've provided a PR and tested in in Seven, Basis, Bartik, Backdrop 5 LIte, and Gin.

**Comment by argiepiano** [comment]
Wonderful! This was such an annoying bug!!! LGTM
