### ISSUE TITLE
Error: Class 'RulesLog' not found in rules_update_1000()

### ISSUE THREAD

**Issue by darby3** [backdrop-contrib/rules#185]
I'm trying to Migrate a Drupal 7.92 site using Rules 7.x-2.13 to a fresh Backdrop 1.23.0 site using Rules 1.x-2.3.2. When I get to the core/update.php step I'm getting an error:

```Internal Server Error ResponseText: Error: Class 'RulesLog' not found in rules_update_1000() (line 205 of /var/www/html/modules/contrib/rules/rules.install).```

Feels like I'm missing something basic here? Anyone have ideas?

**Comment by argiepiano** [comment]
That's an error I've never seen before. Apparently `rules.install` is not loading the class `RulesLog`. This class is loaded by Backdrop's autoloader, after it's included in `rules_autoload_info()` in `rules.module`.

This may have to do with the upgrade process itself, or a corrupt rules folder.

I would try the following:
- Remove the rules folder from the `modules` folder. Be sure that rules is not present anywhere else, including  the `sites` folder and subfolders
- Download (manually) the rules module again and put the folder inside `modules/`
- Start the process of upgrade/migration FROM SCRATCH, meaning you need to drop all the site tables from the database you are using for the migration, AND remove the `files/config_XXX` folder

See what happens.

Also, it may be helpful to know what other contrib modules your site has installed.

**Comment by darby3** [comment]
Sorry for the delayed response. I've tried your suggestion, no luck though. 

Out of curiosity I tried using older releases of the module, and just had a clean update process with version 1.x-2.1.5. I haven't checked to see what may have changed in that time that could be the culprit. I can try updating to the current release some time from here to see if that works.

I'm still in the deeply exploratory phase with Backdrop and my use case for Rules is mostly related to server cache clearing, so it may be a while yet before I have direct cases for testing the module's functionality.

Sorry if I'm not being of much help (to myself or anyone else!).

**Comment by jenlampton** [comment]
I'm having the same problem. I'm going to try loading the include file manually to see if that works. The auto-loaded files are not loaded during update time, because updates are intended to only change data (database/config), and should not call any code from within the modules. (Because most modules depend on core from core that is also not loaded at update time)

**Comment by jenlampton** [comment]
I'm not sure why RulesLog was used here at all, we are only pulling a single digit integer so there's no reason to load an external class. PR on the way!

**Comment by argiepiano** [comment]
This fix makes sense to me. The update hook is trying to use a constant defined in a class that hasn't yet been loaded during the upgrade process. Thanks for providing this, @jenlampton! @bugfolder, pls take a look too.

**Comment by bugfolder** [comment]
LGTM.

**Comment by argiepiano** [comment]
Merged.
