### ISSUE TITLE
Public static function optionsList uses deprecated function taxonomy_vocabulary_get_names()

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/rules#186]
Here's the code:

https://github.com/backdrop-contrib/rules/blob/1.x-2.x/ui/ui.data.inc#L675

The function is deprecated:

https://docs.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.module/function/taxonomy_vocabulary_get_names/1

Proposed solution: Use `taxonomy_vocabulary_load_multiple(FALSE)` instead to prevent deprecation nagging in dblog.

**Comment by indigoxela** [comment]
A PR's available now. I have to admit, no idea when that code runs. System updates (eventually cache flush) seems to trigger the nagging.

**Comment by argiepiano** [comment]
Thanks, @indigoxela. The fix is correct and I'll merge.

There is a bigger problem here, for which I'll open a new issue: if you select the action Create a new entity > Taxonomy term Rules should prompt you for the Vocabulary (which is where this code would run). It doesn't.
