### ISSUE TITLE
rules_i18n.test.info specifies wrong test file

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#189]
The file `rules_i18n.tests.info` specifies the test file `rules_scheduler.test`.

This is incorrect; it should be `rules_i18n.test`.

This failed silently in the past, until https://github.com/backdrop/backdrop-issues/issues/5491 got merged, which now flags wrong file paths.

Unfortunately, with the correct file path, the tests run, but fail. Probably because https://github.com/backdrop-contrib/rules/issues/167 is still open.

**Comment by bugfolder** [comment]
Thsi should probably be in a separate issue, but I'll note it here: the first test failure happens because `parent::setUp('rules_i18n')` throws this exception:

```
"Error: Class 'EntityDefaultI18nStringController' not found in 
/mysite/modules/contrib/rules/rules_i18n/rules_i18n.i18n.inc:10
```

And there does not seem to be a definition of class `EntityDefaultI18nStringController` anywhere.

**Comment by argiepiano** [comment]
That's a WIP that @laryn started some time ago: https://github.com/backdrop-contrib/entity_plus/issues/67

**Comment by bugfolder** [comment]
Since both Rules and Ubercart run all the tests (which is a good thing!), this will fail all of those automatic tests, making them way less useful. So as part of this PR, I've added code to not try to enable `rules_i18n` and return early from the tests. Fixing the tests—and of course, the module!—can then be carried out separately.

@laryn, @argiepiano, sound reasonable?

(Incidentally, the automated test for this PR still failed, but it looks like an unrelated issue in Rules UI. Odd, because that test passes on my local.)

**Comment by laryn** [comment]
Sounds reasonable, absolutely. (I will also say sorry about those stale WIPs and consider them fair game for taking over if at all interested. My Backdrop work has shifted and I don't have the same sites as I used to under my care, so my development focus is also shifting somewhat.)

**Comment by argiepiano** [comment]
Sounds good! I can take a look at that Entity Plus work with i18n. @laryn, thanks for starting those!

**Comment by bugfolder** [comment]
Great, thanks. I'll merge the PR.
