### ISSUE TITLE
Rules UI tests failing

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#191]
RulesUITestCase is failing with several exceptions like this:

EXCEPTION: Undefined index: #description | Notice | user.theme.inc | 129 | theme_user_admin_permissions()

The problem is that in file ui.core, function `RulesPluginUI::settingsFormPermissionMatrix()`, the `#description` property is not being set. PR to follow.

**Comment by bugfolder** [comment]
One can also produce this error in the dblog by visiting admin/config/workflow/rules/components/manage/NN for a component.

**Comment by argiepiano** [comment]
Wow, is that because of issue 980 (https://github.com/backdrop/backdrop-issues/issues/980) that was merged just yesterday? That's going to break TONS of custom modules that define permissions. I can't believe nobody caught that....

**Comment by bugfolder** [comment]
> Wow, is that because of issue 980 (https://github.com/backdrop/backdrop-issues/issues/980) that was merged just yesterday?

Yes. The offending line (line 129 of user.theme.inc) is new in the PR https://github.com/backdrop/backdrop/pull/4292/files.

**Comment by bugfolder** [comment]
The PR fixes the problem for Rules module—all tests now pass—so I'm going to go ahead and merge it. (Which, I hope, will then allow Ubercart tests to pass.)

**Comment by bugfolder** [comment]
> That's going to break TONS of custom modules that define permissions.

Some, perhaps. Core seems happy to handle rendering of permissions that lack the `description` property. The problem here was ui.core.inc was using `theme_user_admin_permissions()` to render the permission, but didn't set up the theme properties to include `#description`.

I did a quick search through the various contrib modules I touch. Looks like `field_permissions_permissions_matrix()` does something similar (no `#description` property).
