### ISSUE TITLE
Entity Load Multiple needed

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/rules#194]
This is just from a spot-check, not from an error I received while using the module, but [this line](https://github.com/backdrop-contrib/rules/blob/1.x-2.x/includes/rules.core.inc#LL305C15-L305C15) looks like it should be using `entity_load_multiple`:

```
    $configs = $ids ? entity_load('rules_config', $ids) : array();
```

**Comment by argiepiano** [comment]
Hi @laryn. Agreed, though in Backdrop `entity_load` is prepared to handle arrays. In fact it calls `entity_load_multiple()`

```php
  if (is_array($id) || $id === FALSE || $id === NULL) {
    return call_user_func_array('entity_load_multiple', func_get_args());
  }
```

**Comment by laryn** [comment]
@argiepiano I retract, you're right and there are a bunch of other places that do the same in the module...
