### ISSUE TITLE
Rules I18n tests don't pass

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#198]
The "Rules I18n" tests don't pass. The first error is "FAIL: Enabled modules: rules_i18n" in RulesI18nTestCase->setUp().

Presumably part of that is because `rules_i18n` module has a dependency of module `entity_plus_i18n`, which, as far as I can tell, doesn't exist in Backdrop (at least, it's not in the `i18n` or `entity_plus` groups).

**Comment by argiepiano** [comment]
Hmm.. `entity_plus_i18n` does exist. It's now a separate submodule. See [this](https://github.com/backdrop-contrib/entity_plus/tree/1.x/modules/entity_plus_i18n). In D7, it was not.  Let's take a look...

**Comment by argiepiano** [comment]
@bugfolder, checking the latest PR, I'm seeing all tests passing. Am I missing something?

<img width="845" alt="Screen Shot 2023-06-18 at 9 22 53 PM" src="https://github.com/backdrop-contrib/rules/assets/9938978/a107fdb7-5a05-4e65-a304-a664ffbbd53c">

**Comment by bugfolder** [comment]
They weren't passing on a local, fresh B installation for me. So maybe it's my local?

**Comment by bugfolder** [comment]
Yes, it was. my Entity Plus repo was out of date. Never mind. (Doi.)
