### ISSUE TITLE
call_user_func(): Argument #1 ($callback) must be a valid callback, class RulesDataUI does not have a method "render" 

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/rules#200]
Just create a test components like shown below:

![Screenshot 2023-09-23 at 2 11 07 AM](https://github.com/backdrop-contrib/rules/assets/56604405/377b08a8-fcf5-4c86-bd0f-145c839f02b7)

and then for any reason clear the data type, label, machine name like shown below:

![Screenshot 2023-09-23 at 2 11 31 AM](https://github.com/backdrop-contrib/rules/assets/56604405/50b793b1-21b1-46b7-babc-2e0e3d30fc1e)

save it and you won't be able to edit the component anymore, because UI breaks like this:

![Screenshot 2023-09-23 at 2 13 48 AM](https://github.com/backdrop-contrib/rules/assets/56604405/c5154784-af19-4432-a4d4-2248e134130a)

**Comment by argiepiano** [comment]
I'm not able to reproduce. When I clear the Data type and select the two --, then try to save I get "Data type is required", but no fatal error. 

Perhaps there is something else at play here? Does the component have any condition or actions already?

**Comment by argiepiano** [comment]
Chronology of captures:

<img width="773" alt="Screen Shot 2023-09-23 at 8 13 58 AM" src="https://github.com/backdrop-contrib/rules/assets/9938978/ab09f1c7-74e7-4901-84ef-d3c1a77c1f26">

Then

<img width="998" alt="Screen Shot 2023-09-23 at 8 13 53 AM" src="https://github.com/backdrop-contrib/rules/assets/9938978/9dff2f8f-21cb-4498-917a-9e8c2058fe8b">


Then Save
<img width="1056" alt="Screen Shot 2023-09-23 at 8 14 08 AM" src="https://github.com/backdrop-contrib/rules/assets/9938978/e8fc83af-0ce1-44ef-96d2-7e24e3bc3002">

**Comment by alanmels** [comment]
Did you save the whole thing without removing anything first? I only cleared the data type, label, machine name after saving and revisiting the rule. And when data type, label, machine name are gone then UI breaks.

**Comment by bugfolder** [comment]
I, too, tried this and was unable to reproduce it. 

* I first created the condition and saved it. 
* I then went back to the main Components screen and selected "Edit ".
* Went to its Settings and cleared the data type, label, and machine name.
* Saved.

It saved correctly with no errors or warnings.

@alanmels, since there have been some new releases in Rules and supporting modules (e.g., E+) since you posted this issue, can you check whether it's still a problem?

**Comment by alanmels** [comment]
To say frankly, I don't remember the details of how this issue popped up. Let's just close this until someone else confirms it.
