### ISSUE TITLE
How to get a component to the parent rule?

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/rules#201]
Hello! Consider this simple rule that loops users to send notification messages:

```
{ "rules_test_notify" : {
    "LABEL" : "Test_notify",
    "PLUGIN" : "reaction rule",
    "ACTIVE" : false,
    "OWNER" : "rules",
    "REQUIRES" : [ "rules" ],
    "ON" : { "node_update--lemonade" : { "bundle" : "lemonade" } },
    "DO" : [
      { "LOOP" : {
          "USING" : { "list" : [ "node:field-drinkers" ] },
          "ITEM" : { "drinker" : "drinker" },
          "DO" : [
            { "mail" : {
                "to" : "[drinker:mail]",
                "subject" : "Test message title",
                "message" : "Test message body",
                "langcode" : [ "" ]
              }
            }
          ]
        }
      }
    ]
  }
}
```

It works just fine, however to send notifications only to users who opted in I need to get a condition check within the loop. Now I've created a component rule that checks if a user wants to receive notifications or now, but I don't seem to be able to find anywhere on the parent rules UI a possibility to trigger the component rule. Per https://www.beyondspotsanddots.com/using-rules-components-drupal-7-even-beginners: 

> Now, how do you "call" this component? Unlike traditional rules, it has no event associated. Here's how: you re-enter your "parent" rule and, in the Actions section, navigate to the "Components" heading in the <select> menu and find the component you created. Once you do that, Rules will ask you to provide values for the parameters the component is asking for. 

*** This part is not quote, but for some reason it's sticking to the above section ***

I looked high and low, but can't find the newly created component anywhere on the main rule's page. Could anyone give me any further pointers if it's somewhere there or is Backdrop version of this module not ready to use components yet?

**Comment by argiepiano** [comment]
@alanmels I've done something like this in D7. I'm trying to reproduce your context. Can you tell me what type of field `field_drinkers` is?

**Comment by alanmels** [comment]
Thanks for taking a look at this. It’s entity reference pointing to users.Sent from my iPhoneOn Sep 23, 2023, at 8:44 AM, Alejandro Cremaschi ***@***.***> wrote:﻿
@alanmels I've done something like this in D7. I'm trying to reproduce your context. Can you tell me what type of field field_drinkers is?

**Comment by argiepiano** [comment]
Got it. This is how I do it:

The main rule that gets triggered by saving the node:
<img width="1136" alt="Screen Shot 2023-09-23 at 7 53 38 AM" src="https://github.com/backdrop-contrib/rules/assets/9938978/bf115fc2-ded8-4170-a478-40a8f22362a7">

The component:
<img width="1128" alt="Screen Shot 2023-09-23 at 7 54 21 AM" src="https://github.com/backdrop-contrib/rules/assets/9938978/95781f84-72f3-42c3-9e35-abc314939c39">

**Comment by argiepiano** [comment]
The user has a field `field_receive_email` boolean which is checked. 

These are the exports:
Main rule
```
{ "rules_send_lemonade_email" : {
    "LABEL" : "Send lemonade email",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules" ],
    "ON" : { "node_insert--lemonade" : { "bundle" : "lemonade" } },
    "IF" : [
      { "entity_has_field" : { "entity" : [ "node" ], "field" : "field_drinkers" } }
    ],
    "DO" : [
      { "LOOP" : {
          "USING" : { "list" : [ "node:field-drinkers" ] },
          "ITEM" : { "list_item" : "Current list item" },
          "DO" : [
            { "component_rules_send_email_to_authorized_user" : { "user" : [ "list-item" ] } }
          ]
        }
      }
    ]
  }
}
```

Component:
```
{ "rules_send_email_to_authorized_user" : {
    "LABEL" : "Send email to authorized user",
    "PLUGIN" : "rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules" ],
    "USES VARIABLES" : { "user" : { "label" : "user", "type" : "user" } },
    "IF" : [
      { "entity_has_field" : { "entity" : [ "user" ], "field" : "field_receive_emails" } },
      { "data_is" : { "data" : [ "user:field-receive-emails" ], "value" : "1" } }
    ],
    "DO" : [
      { "mail" : {
          "to" : [ "user:mail" ],
          "subject" : "Test email",
          "message" : "This is a test.",
          "langcode" : [ "" ]
        }
      }
    ]
  }
}
```

**Comment by argiepiano** [comment]
Be sure to use `Add action` in the **dropbutton of the loop**, not the one at the bottom of the table.
<img width="991" alt="Screen Shot 2023-09-23 at 7 56 54 AM" src="https://github.com/backdrop-contrib/rules/assets/9938978/9f557836-9d79-46f6-afb9-219dd8b1a8e6">

**Comment by alanmels** [comment]
@argiepiano, thank you very much as I finally see the component on the main rule side. My mistake was that I chose Condition set instead of Rule when creating a component. Unfortunately, no detailed documentation about creating components around.

**Comment by alanmels** [comment]
@argiepiano, can you help me to address one more step at this? 

The initial rule was easily passing node data to the mailing loop, because of the _After updating existing content of type Lemonade_ event. Now when when the Send mail action is moved to the component, all those replacement patterns like [node:title] of [node:field-anything] in the subject line or body of the Send mail component are failing. Trying to add the Lemonade node to the Send mail component is not working for me because whatever I do the data selector is tied to the user and not to the node.

**Comment by argiepiano** [comment]
You need to accept a node as the second parameter in the component.

<img width="1222" alt="Screen Shot 2023-09-23 at 4 56 55 PM" src="https://github.com/backdrop-contrib/rules/assets/9938978/a45dcb76-d317-48cf-a3b2-6ae7759838c1">

Once that's in place for the component, then you need to select the node in the action within the loop:

<img width="928" alt="Screen Shot 2023-09-23 at 4 57 33 PM" src="https://github.com/backdrop-contrib/rules/assets/9938978/538ccc68-b8df-4d8b-a4d3-f7d5ac1667d1">

**Comment by argiepiano** [comment]
Here's the export of the Rule with the loop:

```
{ "rules_send_lemonade_email" : {
    "LABEL" : "Send lemonade email",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules" ],
    "ON" : { "node_insert--lemonade" : { "bundle" : "lemonade" } },
    "IF" : [
      { "entity_has_field" : { "entity" : [ "node" ], "field" : "field_drinkers" } }
    ],
    "DO" : [
      { "LOOP" : {
          "USING" : { "list" : [ "node:field-drinkers" ] },
          "ITEM" : { "list_item" : "Current list item" },
          "DO" : [
            { "component_rules_send_email_to_authorized_user" : { "user" : [ "list-item" ], "node" : [ "node" ] } }
          ]
        }
      }
    ]
  }
}
```

And the component that sends the email:

```
{ "rules_send_email_to_authorized_user" : {
    "LABEL" : "Send email to authorized user",
    "PLUGIN" : "rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules" ],
    "USES VARIABLES" : {
      "user" : { "label" : "user", "type" : "user" },
      "node" : { "label" : "node", "type" : "node" }
    },
    "IF" : [
      { "entity_has_field" : { "entity" : [ "user" ], "field" : "field_receive_emails" } },
      { "data_is" : { "data" : [ "user:field-receive-emails" ], "value" : "1" } }
    ],
    "DO" : [
      { "mail" : {
          "to" : [ "user:mail" ],
          "subject" : "Test email",
          "message" : "This is a test.",
          "langcode" : [ "" ]
        }
      },
      { "backdrop_message" : { "message" : "Rule component ran!" } }
    ]
  }
}
```

**Comment by argiepiano** [comment]
(Updated the answer as I pasted the wrong thing)

**Comment by alanmels** [comment]
So simple! I rarely used Rules for simple things preferring coding for more complex staff, but now I'm starting to actually like the module. Thank you again very much, @argiepiano, works like a charm!

> You need to accept a node as the second parameter in the component.
> <img alt="Screen Shot 2023-09-23 at 4 56 55 PM" width="1222" src="https://user-images.githubusercontent.com/9938978/270136583-a45dcb76-d317-48cf-a3b2-6ae7759838c1.png">
> 
> Once that's in place for the component, then you need to select the node in the action within the loop:
