### ISSUE TITLE
Make tabs persistent on edit pages

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/rules#202]
This is not that important feature request.

Every time you click on specific Rule or Component the tabs on top are gone and after making changes and saving you have to navigate back the respective list of Rules or Component using admin bar or modifying the URL. Not a big deal, but still would be more comfortable to have those tabs persistent everywhere on Rules pages.

![Screenshot 2023-09-23 at 9 41 17 PM](https://github.com/backdrop-contrib/rules/assets/56604405/ab582077-de1a-4b42-ac56-8f4fdebf434c)

**Comment by argiepiano** [comment]
I see your point, but that's not possible given how core handles those tabs. Those tabs are shown only when you are displaying the page at a specific set of paths. In this case, that set of paths is:
- `admin/config/workflow/rules/reaction` (default tab, aka as `admin/config/workflow/rules`, which is the base for the set)
- `admin/config/workflow/rules/components`
- and `admin/config/workflow/rules/settings`

All three use the same base, and have been defined as either type `MENU_LOCAL_TASK` or `MENU_DEFAULT_LOCAL_TASK`. 

While less convenient, I usually click on the breadcrumb to go back (which is more convenient than using the admin bar).

Two possible solutions:
- Create a set of secondary "local tasks" (which are the set of secondary tabs below the primary ones) for each rule. If you do this and you have many rules, the screen becomes unmanageable. But at least you'll still see the primary tabs in the edit screen
- OR, re-route to the main Rules or Components page after "Save changes" to a rule. This could be extremely annoying when you are building the rule, though.  

BTW, the same "problem" happens with Layouts. Once you enter the edit screens, you won't see the tabs that include "List Layouts". Again, it's a core UI thingy, the results of how and when those tabs are built.

**Comment by alanmels** [comment]
Fair enough. I'll re-enable crumbs on admin pages because of this one.
