### ISSUE TITLE
Invokes undefined function `entity_var_json_export`

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/rules#203]
This happens in `RulesPlugin::__toString()`. The function name in Backdrop's Entity Plus is `entity_plus_var_json_export()`.

**Comment by argiepiano** [comment]
PR ready. #204

**Comment by argiepiano** [comment]
Since this is an obvious problem with a mistyped function name, I'm going to merge this. @laryn, @bugfolder, let me know if you have any concerns with this.

**Comment by laryn** [comment]
LGTM, thanks @argiepiano.
