### ISSUE TITLE
PHP 8.2 dynamic properties deprecation messages 

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/rules#205]
Class `RulesPlugin` uses a number of dynamic properties. The easiest solution is to include `#[\AllowDynamicProperties]` before the class definition. This is how D7 fixed it 2 months ago. See https://git.drupalcode.org/project/rules/-/commit/716e86463307a64d660f5dce53dcc0727747d7fe

There are a couple of other test fixes for the same reason, in that commit. PR coming.

**Comment by argiepiano** [comment]
PR #206 ready for review.

Should we update the automated tests to run on PHP 8.2?

**Comment by indigoxela** [comment]
While working on something unrelated, I ran into several deprecation notices today, all caused by RulesReactionRule. Perfect opportunity to test this PR. :wink: 

Example of such nagging:
```
    Deprecated function: Creation of dynamic property RulesReactionRule::$active is deprecated in BackdropDatabaseCache->prepareItem() (line 512 of core/includes/cache.inc).
    Deprecated function: Creation of dynamic property RulesReactionRule::$status is deprecated in BackdropDatabaseCache->prepareItem() (line 512 of core/includes/cache.inc).
    Deprecated function: Creation of dynamic property RulesReactionRule::$dirty is deprecated in BackdropDatabaseCache->prepareItem() (line 512 of core/includes/cache.inc).
    Deprecated function: Creation of dynamic property RulesReactionRule::$module is deprecated in BackdropDatabaseCache->prepareItem() (line 512 of core/includes/cache.inc).
    Deprecated function: Creation of dynamic property RulesReactionRule::$owner is deprecated in BackdropDatabaseCache->prepareItem() (line 512 of core/includes/cache.inc).
    Deprecated function: Creation of dynamic property RulesReactionRule::$access_exposed is deprecated in BackdropDatabaseCache->prepareItem() (line 512 of core/includes/cache.inc).
    Deprecated function: Creation of dynamic property RulesReactionRule::$tags is deprecated in BackdropDatabaseCache->prepareItem() (line 512 of core/includes/cache.inc).
```
Patch applied, flushed caches again, tried to trigger... but there was silence. No more nagging.

I don't feel qualified to *review* the code (AllowDynamicProperties seems a shortcut), but I can confirm that this works for me. :+1:

**Comment by indigoxela** [comment]
Friendly reminder, that without this patch applied, Rules UI is almost unusable on PHP 8.2 :wave: 

The README lists 4 maintainers, of which only one seems inactive on GitHub, so there's still hope, that this bug might get fixed.

**Comment by argiepiano** [comment]
Thanks, @indigoxela. Does the PR still fixes the issue for you?

**Comment by argiepiano** [comment]
OK, I tested again, and it works. Given that you gave this PR a thumbs up earlier, I'm going to merge this now. @bugfolder, @laryn, it may be time for a new release. What think you all?

**Comment by laryn** [comment]
> it may be time for a new release

@argiepiano Yes, looks like there are a few fixes merged that would be good to get out there 👍

**Comment by bugfolder** [comment]
> ...it may be time for a new release. What think you all?

Agreed.

**Comment by argiepiano** [comment]
New release is out!
