### ISSUE TITLE
RulesPlugin::setParent(): Argument #1 ($parent) must be of type RulesContainerPlugin, RulesCondition given

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/rules#207]
Consider a node having a date field with the "Collect an end date" option enabled, and you want to do something whenever either of starting or ending date is changed. So your rule would be this one:

```
{ "rules_test" : {
    "LABEL" : "test",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules" ],
    "ON" : { "node_update--post" : { "bundle" : "post" } },
    "IF" : [
      { "NOT data_is" : {
          "data" : [ "node:field-date:value" ],
          "value" : [ "node-unchanged:field-date:value" ]
        }
      },
      { "NOT data_is" : {
          "data" : [ "node:field-date:value2" ],
          "value" : [ "node-unchanged:field-date:value2" ]
        }
      }
    ],
    "DO" : []
  }
}
```

but with an OR condition between two "[NOT Data comparison]" conditions as otherwise it won't trigger. The whole problem is about introducing this OR condition.

If you put it like shown in the screenshot (that is without indentation) then it never gets to trigger the action part:

![Screenshot 2023-09-24 at 7 40 00 PM](https://github.com/backdrop-contrib/rules/assets/56604405/066b84a2-8bb2-43e3-b977-2bd72b6411ec)

So try to move it slightly to the right like this:

![Screenshot 2023-09-24 at 7 31 10 PM](https://github.com/backdrop-contrib/rules/assets/56604405/9d33c1c7-fdda-4a7e-ace0-8834a09fc13e)

save changes and you will get the error message:

```
Error
RulesPlugin::setParent(): Argument #1 ($parent) must be of type RulesContainerPlugin, RulesCondition given, called in /home/username/public_html/modules/contrib/rules/ui/ui.core.inc on line 1074 
```

**Comment by argiepiano** [comment]
OR and AND conditions are a little funky looking. They "wrap" all the options **indented below themselves**. The first option NOT indented will not be part of the OR.

<img width="1232" alt="Screen Shot 2023-09-24 at 7 05 26 PM" src="https://github.com/backdrop-contrib/rules/assets/9938978/ddc4cd55-bb3a-46b6-afda-f4c62de983a5">

**Comment by argiepiano** [comment]
Check out this page and video (about 5:20)
https://drupalize.me/tutorial/combining-conditions

BTW, this is an EXCELLENT guide. It will answer most of these questions you've been having :)

https://www.drupal.org/node/1866108

**Comment by alanmels** [comment]
Hm, had no idea. I'll give it a try later today. But don't you think UI should not give that error anyway? Maybe the error could be caught to give an explanation warning to user instead? 

> OR and AND conditions are a little funky looking. They "wrap" all the options **indented below themselves**. The first option NOT indented will not be part of the OR.

**Comment by argiepiano** [comment]
> But don't you think UI should not give that error anyway? Maybe the error could be caught to give an explanation warning to user instead?

Agreed! The D7 version has the same problem. @alanmels, Rules is a very complex module with a huge web of classes that extend each other, etc. If you have any thoughts or ideas on how this fatal error can be prevented, I'd love to merge your PR.

**Comment by argiepiano** [comment]
Thanks, @alanmels! Can you please check the ui test failure? The change seems to have created a problem with the automated test.

**Comment by alanmels** [comment]
I've re-run the test and it failed again https://github.com/backdrop-contrib/rules/actions/runs/6302294027/job/17109159053?pr=208#step:13:41 No idea how to fix this, but I'm totally ok if PR doesn't go in.

**Comment by alanmels** [comment]
After I made a slight change, it passed all checks this time https://github.com/backdrop-contrib/rules/pull/208 But I am not sure if it's the right solution, so please double check if it works for you too as UI-wise it totally worked for me.

**Comment by argiepiano** [comment]
@alanmels thanks for providing the PR. I think this is on the right track. The issue happens when you first add the AND or OR element - the browser's  tabledrag doesn't yet recognize that those can't be moved under RuleCondition children. After you save the form, actually you can't move the AND or OR under a condition - tabledrag doesn't allow it. 

So, I think the PR looks fine, except that I think it can be simpler. You are checking for the parent's parent's element to see if it's root etc. In my testing I think the only needed check is that the parent is not a RuleCondition (AFAIK there are no circumstances where and AND or an OR can be have a condition as a parent). 

So, can you test the following, simpler if structure?

```php
        // Parents should never be RulesCondition.
        if ($parent->pluginInfo()['class'] == 'RulesCondition') {
          backdrop_set_message(t('The <em>OR</em> and <em>AND</em> elements should "wrap" all the conditions indented below themselves. <em>OR</em> and <em>AND</em> cannot be indented below a condition. ', 'warning'));
        }
        else {
          $child->setParent($parent ? $parent : $this->element);
        }
```

So, this would replace your code. (I also changed the type of message to warning and changed the language a bit).

**Comment by alanmels** [comment]
@argiepiano, I really had to move on and don't have time for even testing. Please feel free to make necessary changes to the PR and push it forward if you believe it works.

**Comment by bugfolder** [comment]
I've implemented the change suggested by @argiepiano in a new PR (slightly tweaked the wording). Tests pass.

**Comment by argiepiano** [comment]
Since I suggested this change, I think someone else should review it. I'm a bit wary of making changes to any of the Rules classes unless absolutely needed. This is such a complex web of classes that changes are prone to break things. This error only happens if the AND or OR are inserted in incorrect ways.

**Comment by bugfolder** [comment]
@laryn, @Graham-72, either of you up to review? (And also, should we do a new release after this passes review?)

**Comment by laryn** [comment]
LGTM
