### ISSUE TITLE
Action to create Taxonomy term does not prompt user for the Vocabulary

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/rules#210]
When you use the action "Create a new entity" and then select Taxonomy Term, Rules should prompt you to select a Vocabulary. It does on D7, but not on Backdrop:

Drupal 7
<img width="762" alt="Screen Shot 2024-03-26 at 8 23 09 AM" src="https://github.com/backdrop-contrib/rules/assets/9938978/00cb58c8-c74b-4415-af6a-0fcf70d18bd1">

Backdrop:
<img width="755" alt="Screen Shot 2024-03-26 at 8 23 46 AM" src="https://github.com/backdrop-contrib/rules/assets/9938978/b24cd150-cb8c-413c-b521-7e1ddbd7f9b6">

**Comment by argiepiano** [comment]
OK, I've discovered the problem. It's in the property definition for taxonomy terms provided by Entity Plus. I'll open an issue there, but will leave this open until that issue is merged.

**Comment by argiepiano** [comment]
Entity Plus' issue created and PR provided: https://github.com/backdrop-contrib/entity_plus/issues/171

**Comment by bugfolder** [comment]
I can confirm that with the changes in the latest release of Entity Plus, the Vocabulary is now being prompted:

![image](https://github.com/backdrop-contrib/rules/assets/29214084/2acd973d-ba30-4403-ab90-ee5abf66aa6b)

Closing this issue. Thanks, @argiepiano!
