### ISSUE TITLE
Add support for CC, BCC, Reply-to to "Send mail" actions

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#211]
I've encountered the situation where I need to set the "Reply-to" header in a Rules-sent mail to something other than the "from" address. It would be nice to be able to set this in the "Send mail" action configuration. Similarly, I could imagine others wanting to add CC or BCC to Rules-sent mails.

We can add these parameters to the `mail`and `mail_to_users_of_role` actions and maintain backward compatibility by marking the new parameters with the `allow null` property.

The PR (to follow) adds the new parameters and provides tests for them as well (in addition to the existing tests that don't set those new parameters and therefore test B/C).

**Comment by argiepiano** [comment]
Thanks for the patch! Very useful. LGTM

**Comment by bugfolder** [comment]
There's a corresponding D7 issue here:

https://www.drupal.org/project/rules/issues/3390275
