### ISSUE TITLE
Wrong invocation of RulesEvaluationException... (use placeholders)

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#224]
Backdrop version of  [Issue ](https://git.drupalcode.org/project/rules/-/commit/1b5a0308f1ff1edfa00e5aeedb876cfe528f973b)[#3256912](https://www.drupal.org/i/3256912)[ by klausi, TR: Wrong invocation of RulesEvaluationException...](https://git.drupalcode.org/project/rules/-/commit/1b5a0308f1ff1edfa00e5aeedb876cfe528f973b).

Part of https://github.com/backdrop-contrib/rules/issues/221.

Some of these were already in place, but I've reviewed all invocations of RulesEvaluationException, fixed a few stragglers, and made all wrapping consistent.

**Comment by argiepiano** [comment]
LGTM
