### ISSUE TITLE
Don't read in a View from a file in rules_scheduler_update_1201()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#228]
In [this Zulip message](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Office.20Hours/near/434539966), we see this error:

>Error page:
>Warning: file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in rules_scheduler_update_1201() (line 120 of /mysite/modules/rules/rules_scheduler/rules_scheduler.install).
>
>Warning: file_get_contents(http://backdrop.bps-al.org/modules/rules/rules_scheduler/config/views.view.rules_scheduler.json): Failed to open stream: no suitable wrapper could be found in rules_scheduler_update_1201() (line 120 of /mysite/modules/rules/rules_scheduler/rules_scheduler.install).
>
>The update process was aborted prematurely while running update '#'1201 in rules_scheduler.module. All errors have been logged. You may need to check the watchdog database table manually.

What was supposed to happen was that `rules_scheduler_update_1201()` reads in a missing View from the json config file, which was issue https://github.com/backdrop-contrib/rules/issues/215. The fix was to read in the missing View from its config file in the update.

In the issue discussion, it was suggested that reading in a config from a file, rather than explicitly pasting in the code, was risky. This risk seems to have been borne out.

(I think the solution is to fix update 1201, rather than add a new `hook_update_N`.)

**Comment by bugfolder** [comment]
PR added. To test, delete the Rules Schedule View, then edit the `system` table and set the schema version back to 1200, so that update 1201 will re-run if it hasn't yet. If it did successfully run, then everything should be working OK.

**Comment by argiepiano** [comment]
@bugfolder thanks for this! Please see my comment in the PR.

**Comment by argiepiano** [comment]
LGTM!
