### ISSUE TITLE
Importing a rule from a file doesn't save the rule.

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#230]
If you try importing a rule from a file via `admin/config/workflow/rules/reaction/import_file`, although the process completes with no errors, the status message says the rule was imported, and watchdog log reports that it was imported, it was never saved to the db and therefore doesn't exist.

However, importing the rule by pasting its data in via `admin/config/workflow/rules/reaction/import` works just fine.

This appears to be because the function `rules_ui_import_file_form_submit()` is missing the call to `$rules_config->save()` that is present in function `rules_ui_import_form_submit()`. And indeed, copying the same code over fixes the problem.

A test rule for importing (to verify the issue) is attached.

PR to follow.
[rules_test_rule.json](https://github.com/backdrop-contrib/rules/files/15140226/rules_test_rule.json)

**Comment by argiepiano** [comment]
Thanks, @bugfolder. LGTM. Incidentally, the file upload widget should be required. Otherwise you get a fatal error when submitting without having selected a file. I'll open a new issue.
