### ISSUE TITLE
Add Bee commands to Rules module.

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#232]
It would be nice to provide Bee commands to the Rules module. Initially, I suggest adding "Enable a rule" and "Disable a rule", which I've created in the following PR, but I can imagine we might want to follow on with additional commands.

**Comment by argiepiano** [comment]
Looks great. Thanks

**Comment by bugfolder** [comment]
Thanks for approving. I don’t have web access to GH for the next week and a half, so can’t do the new release myself until I return.
