### ISSUE TITLE
Add "clear Rules cache" to admin bar menu

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#236]
When developing Rules, one needs to clear the Rules cache after making a code change. Rather than clearing all caches (the only way currently), it would be nice to be able to clear just the Rules cache via the admin bar, by adding a "Rules" entry to the "Flush all caches" submenu.

This is easily done by adding an implementation of `hook_admin_bar_cache_info()`.

**Comment by argiepiano** [comment]
Good idea! LGTM!
