### ISSUE TITLE
Errors and Blank Screen when Adding Action

### ISSUE THREAD

**Issue by Dinornis** [backdrop-contrib/rules#24]
Adding an action to rule set generates blank screen with the following error shown in log:
```
LOCATION: /admin/config/workflow/rules/components/manage/4
REFERRER: /admin/config/workflow/rules/components
MESSAGE: Notice: Undefined index: label in RulesUICategory::getOptions()
(line 1231 of /modules/rules/ui/ui.core.inc)
```
**To replicate:**
1.	Go to `/admin/config/workflow/rules/components` `Add new component`
2.	Select `Rule set` for the `Component plugin` field
3.	Click `CONTINUE`
At this point Backdrop reports:
```
LOCATION: /admin/config/workflow/rules/components/add
REFERRER: /admin/config/workflow/rules/components/add
MESSAGE	Notice: Undefined index: label in RulesUICategory::getOptions()
(line 1231 of /modules/rules/ui/ui.core.inc).
```

4.	Name the Rule set
5.	For `Variables` select `Node` and click `CONTINUE`
At this point Backdrop reports:
```
LOCATION: /admin/config/workflow/rules/components/manage/rules_test_rule_set
REFERRER: /admin/config/workflow/rules/components/add
MESSAGE	Notice: Undefined index: label in RulesUICategory::getOptions()
(line 1231 of /modules/rules/ui/ui.core.inc).
```
and
```
LOCATION: /admin/config/workflow/rules/components/manage/rules_test_rule_set
REFERRER: /admin/config/workflow/rules/components/add
MESSAGE	Warning: file_get_contents(core/modules/user/user.permissions.js):
failed to open stream: No such file or directory in backdrop_build_js_cache()
(line 5383 of /core/includes/common.inc).
```

6.	Click on `Add rule`
7.	Name the rule and click `SAVE CHANGES`
8.	Click `Add condition`
9.	Select `Node` > `Content is published` as condition
10.	Select `node` as `Data selector` and click `SAVE`
11.	Click `Add condition`
12.	Select `Node` > `Content is of type` as condition
13.	Select the desired content type and click `SAVE`
14.	Click `Add action`
At this point I get a blank screen with no additional errors in log.

**Comment by Graham-72** [comment]
I'm thinking this is no longer an issue. Please re-open if necessary.
