### ISSUE TITLE
Export/Import rules config via a file

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/rules#25]
We've kept the old CTools import/export UI. We should ditch that and use core CMI.

**Comment by jackaponte** [comment]
Hi folks! Rules configurations in CMI would be very helpful for one project we're working on; do maintainers have any plans to work on this in the near future?

**Comment by jackaponte** [comment]
> Hi folks! Rules configurations in CMI would be very helpful for one project we're working on; do maintainers have any plans to work on this in the near future?

Ping! :)

**Comment by Graham-72** [comment]
I haven't yet made any definite plan to do this but will try in the next few weeks. Do you have a 'need by' date?

**Comment by jackaponte** [comment]
Thanks for the response @Graham-72! I'm looping in @kelizoliva who is more likely to have an idea of a "need by" date for this.

**Comment by kelizoliva** [comment]
There is no hard need-by date, no. We are working on deploying many identical containerized Backdrop and CiviCRM instances for several affiliates in a large organization, for which some rules will be needed for near-future milestones (that would be deployed across all instances), so if this was available in the next month or two, that would be spectacular!

**Comment by Graham-72** [comment]
Thanks for your responses. I now hope to take an initial look at this before the end of this month (October).

**Comment by Graham-72** [comment]
@jackaponte @kelizoliva I have now taken a first look at this and am feeling very much out of my depth! This is because it seems that the config information for a rule is processed and stored as an entity, involving entity module functions. Please could you explain a bit more about what you need to do? Are you hoping to copy a predefined rule into several sites? Maybe the existing rule export/import mechanism can help, or be adapted to meet your need?

**Comment by kelizoliva** [comment]
@Graham-72 the sites are deployed as part of a script. We don't actually log into the sites at all, the idea is that all the configuration is completed in the automated deployment. If there was a way to import rules via the cli, that would be acceptable, though I am not aware of any method by drush or the backdrop cli that would accomplish this.

**Comment by docwilmot** [comment]
> This is because it seems that the config information for a rule is processed and stored as an entity, involving entity module functions.

The config would just be how the information about the Entity is stored. For example Layout stores info about its Objects in config; they're not Entities, but Entities are just other Objects. The loading and saving should be similar. Wonder if you'd be able to say what you found prohibitive about this conversion to config?

**Comment by docwilmot** [comment]
Ah nevermind, actually looked at `rules_config_load()` and I see what you mean.

**Comment by Graham-72** [comment]
> Wonder if you'd be able to say what you found prohibitive about this conversion to config?

It seemed to me, and I may well be wrong, that Rules is relying on the Entity module to write config data into the rules_config data table. I wouldn't want to be changing the Entity module because of the needs of a contributed module.

**Comment by Graham-72** [comment]
@kelizoliva 

> the configuration is completed in the automated deployment
So the Rules module would be installed as part of automatic site build?

Could you then use a pre-configured rules settings file (json type) and have rules.install import all these rules on installation. 

So we need to adapt the Rules export function so you can create the required customised config file. 
Does that sound like a way forward?

**Comment by kelizoliva** [comment]
Yes, the installation of rules is handled by an ansible/docker deployment method, so if we could export a rules config to a file that could then be imported as part of our deployment orchestration, that would be great! 

(also blog(s) entry is forthcoming in 2020 on all the fun things we are doing with backdrop/ansible/docker)

**Comment by Graham-72** [comment]
@kelizoliva I am thinking that it should be possible to add into Rules a variant of its export function that creates a json file that adopts our Backdrop config settings format, and have a corresponding import function that would import one of these, by upload perhaps? This would be in addition to the existing copy and paste facility. Would this fit with your ideas on deployment?

**Comment by Graham-72** [comment]
I think maybe we need to change the title of this issue or create a new one specifically about export/import of Rules configs.

**Comment by kelizoliva** [comment]
I would say that the ability to export the rules config to a file (json or whatever) that could then likewise be imported (preferably with drush commands) would be fantastic. I would support us changing the title on this issue.

**Comment by herbdool** [comment]
> Rules is relying on the Entity module to write config data into the rules_config data table. I wouldn't want to be changing the Entity module because of the needs of a contributed module.

@Graham-72 I don't think it necessarily means that. Nodes are also entities but their config are now stored in files. So one possibility is changing the Rules entity to do that too.

**Comment by Graham-72** [comment]
@kelizoliva I am now having another look at this. Are you likely to want to be able to upload multiple rules as a single file?
The current import facility provides for pasting one rule at a time. Would the equivalent for uploading rule files, i.e. one at a time, meet your need? I am wanting to keep this as simple as possible, at least to start with.

**Comment by kelizoliva** [comment]
Either way is fine by me, so long as it can be done. :) It would be scripted, so it wouldn't actually make a difference to me as a human.

**Comment by Graham-72** [comment]
@kelizoliva I have now produced PR #66 to do this. I would be grateful if you would kindly test this to see if it meets your need. I have only done very simple tests at the moment.  Is it going to be suitable for scripting the upload process you need?

**Comment by herbdool** [comment]
Nice @Graham-72. Now that you've got an import/export working it might not be much more work to convert the whole rule to be stored in JSON files. I think that would be the biggest benefit.

**Comment by Graham-72** [comment]
@herbdool I am closing this issue because the latest PR (66) adds in the export/import of rules as files. I suggest we have a new one for converting the module to store rules as config files, as proposed previously in this issue. But please could you provide some wording to suggest the benefit of doing this? I'm not sure what you have in mind when you write
> I think that would be the biggest benefit.

**Comment by kelizoliva** [comment]
January has been crazy, sorry I did not get a chance to reply sooner. I have not tested this just yet, but would I be able to import a rule via drush (or b) at this point, or do I need to create a ticket for that over on one of those projects?

**Comment by Graham-72** [comment]
Someone else needs to answer this because I am not competent with drush or b. If it needs work please open a new separate issue.

**Comment by serundeputy** [comment]
@kelizoliva @Graham-72 the ability to import/export rules would likely happen here https://github.com/backdrop-contrib/rules/blob/1.x-2.x/rules.drush.inc#L16 ... looks like as of yet there are no import/export commands defined there.

If you end up with the rules in proper backdrop config (maybe that is what @herbdool is suggesting, not sure), then you'd be able to import/export the rules w/ `drush bcim/bcex`. 

Hope that at least clarifies.

**Comment by kelizoliva** [comment]
I agree with @herbdool that converting this to JSON config files would be the best route to go from here, then they could be easily exported and imported via the command line; and in the case of how we would like to use them, deployed across many containerized Backdrop sites at once. I can create a new issue for this.

**Comment by kelizoliva** [comment]
Created #69

**Comment by herbdool** [comment]
@serundeputy yes, that is what I meant. Store it all in CMI (aka JSON files). It might be helpful to see how it was done for Feeds module which also was using CTools for import/export. Feeds was storing config in the db in D7 but converted to CMI.
