### ISSUE TITLE
Change to Entity Plus

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/rules#27]
Should the dependency be changed from [EMW](https://github.com/backdrop-contrib/entity_metadata_wrapper) to [Entity Plus](https://github.com/backdrop-contrib/entity_plus)?

> If your module depends on the module `Entity Metadata Wrapper` in Backdrop contrib, read the following and take steps to change the dependency to [this module](https://github.com/backdrop-contrib/entity_plus) instead.

---
PR by @Laryn: https://github.com/backdrop-contrib/rules/pull/31

**Comment by laryn** [comment]
@Graham-72 I made a bunch of commits (that was messy, I apologize, and hopefully you can squash and merge if it's looking good on your end). I'm done for now so please test whenever you get a chance and see if this works on your end.

**Comment by laryn** [comment]
For the record, part of the reason I think we need to do this is because Entity Plus is the recommended path compared to EMW and when we run into a case where we want to use another module that requires Entity Plus, we won't be able to use that module and Rules at the same time because of conflicts with EMW/E+.

Here's my work on the EntityPlus branch for Rules:
https://github.com/laryn/rules/tree/EntityPlus

**Comment by Graham-72** [comment]
@laryn yes I agree that we should do this.
I have tried installing EntityPlus and your EntityPlus branch of Rules on a test site and I am getting a fatal error giving this report
```
Fatal error: Uncaught Error: Class name must be a valid object or a string in /.../core/modules/entity/entity.module:460 Stack trace: #0 /.../core/modules/entity/entity.module(364): entity_get_controller('rules_config') #1 /.../core/modules/entity/entity.module(392): entity_load_multiple('rules_config', false, Array) #2 
/.../modules/entity_plus/entity_plus.module(510): entity_load('rules_config', false, Array) #3 
/.../modules/rules/rules.module(874): entity_load_multiple_by_name('rules_config', false, Array) #4
 /.../modules/rules/includes/rules.plugins.inc(764): rules_config_load_multiple(false, Array) #5 
/.../modules/rules/rules.module(391): RulesEventSet:: in 
/.../core/modules/entity/entity.module on line 460
```
Have you experienced this?

**Comment by Graham-72** [comment]
On another test site which had previously been working with EMW and Rules and had some existing reaction rules, having tried this change to using EntityPlus I get a similar fatal error but the report gives `RulesEventSet::rebuildEventCache()` as the issue.

**Comment by laryn** [comment]
@Graham-72 I did find I had trouble swapping out EMW and E+ without manually truncating the `cache_bootstrap` table. I'm not sure if that relates to what you are seeing. Does that help in your case?

**Comment by Graham-72** [comment]
@laryn I am concerned that I experienced this problem on a test site that had not previously had Rules or EMW installed, i.e. trying to use the EntityPlus version for the first time. I am going to be away now for 3 weeks and will have another look mid-March.

**Comment by laryn** [comment]
I made a PR of my branch (with some help from @herbdool as well) here: https://github.com/backdrop-contrib/rules/pull/31
