### ISSUE TITLE
Notices when viewing Rules settings page

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/rules#29]
> Notice: Undefined variable: theme_default in rules_admin_settings_submit() (line 232 of /path/modules/rules/rules_admin/rules_admin.inc).

> Notice: Undefined index: rules_debug_region_ in rules_admin_settings_submit() (line 232 of /path/modules/rules/rules_admin/rules_admin.inc).

> Notice: Undefined variable: admin_theme in rules_admin_settings_submit() (line 233 of /path/modules/rules/rules_admin/rules_admin.inc).

PR https://github.com/backdrop-contrib/rules/pull/30

**Comment by Graham-72** [comment]
The debug region and settings have now been removed with fix for issue #35.
