### ISSUE TITLE
Show debug information in a region setting doesn't make sense in Backdrop

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/rules#35]
In Backdrop there are no regions, this is replaced by Layouts, so there needs to be an alternative way of showing the debug information. Is there a block that can be manually added to a layout? Or just show them in a message?

**Comment by Graham-72** [comment]
Now here as PR https://github.com/backdrop-contrib/rules/pull/51

**Comment by Graham-72** [comment]
Fixed subject to code checks, and perhaps change to a lighter colour for background of new custom block.

**Comment by laryn** [comment]
From what I can tell from this thread this is taken care of. Please open a new issue if you find anything remaining that needs attention.
