### ISSUE TITLE
 PHP Fatal error:  Cannot make static method EntityInterface::entityType() non static

### ISSUE THREAD

**Issue by vstemen** [backdrop-contrib/rules#46]
Rules is broken in backdrop 1.13.0.

As soon as I enable rules, it breaks the site and I just get dead white
pages.  drush outputs

    PHP Fatal error:  Cannot make static method EntityInterface::entityType() non static in 
        class RulesConfigEntity in
        /data/htdocs/dev1.mysite.com/modules/rules/includes/rules.core.inc on
        line 21             
    Drush command terminated abnormally due to an unrecoverable error.     [error]
    Error: Cannot make static method EntityInterface::entityType() non static in class 
    RulesConfigEntity in 
    /data/htdocs/dev1.mysite.com/modules/rules/includes/rules.core.inc, line 21             

This is apparently because backdrop now defines that method as static in core.

I have included a patch that fixed it on my site.

**Comment by vstemen** [comment]
I'm not sure if it attached my patch.  I did a select file and it indicated it was attached, but I don't
see a link to it in the issue.  If not, let me know.  I will just post it as text.

**Comment by vstemen** [comment]
I cannot seem to get file attachments to work on github so I am imbeding the
patch here.

    diff --new-file -r --unified=4 rules-1.x-2.1.1/includes/rules.core.inc rules/includes/rules.core.inc
    --- rules-1.x-2.1.1/includes/rules.core.inc	2019-04-22 07:23:06.000000000 -0500
    +++ rules/includes/rules.core.inc	2019-05-30 11:31:02.222953000 -0500
    @@ -29,9 +29,9 @@
     
       /**
        * Implements EntityInterface::entityType().
        */
    -  public function entityType() {
    +  public static function entityType() {
         return 'rules_config';
       }
     
   /**

**Comment by Graham-72** [comment]
Please see issue #44 about the problem with BD 1.13.0

**Comment by vstemen** [comment]
OK.  Thanks.
