### ISSUE TITLE
Fatal error when importing config that removes a Rule

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/rules#47]
I imported config from live to dev. The dev site had a rule but live didn't. So the import will delete the rule from dev. It should work smoothly but I get this fatal error:

> TypeError: Argument 1 passed to rules_config_delete() must be of the type array, object given, called in /app/core/includes/module.inc on line 960 in rules_config_delete() (line 929 of /app/modules/rules/rules.module).

**Comment by Graham-72** [comment]
The function `rules_config_delete()` is calling a non-existent function` entity_plus_get_controller()`. Should this perhaps be `entity_get_controller()` that it calls?

**Comment by herbdool** [comment]
I think you're correct. `entity_get_controller()` exists in core.

**Comment by Graham-72** [comment]
I will try it sometime.

**Comment by herbdool** [comment]
I've got a site that's running the latest release but still getting the same error. When I disable rules I'm able to do a config sync. So I suspect there's something else going on.

**Comment by Graham-72** [comment]
I think there is something wrong with `function rules_config_delete(array $ids)` in rules.module.
Is this not an implementation of `hook_config_delete` in which case the parameter should or will be of type **Config** rather than **array**?

**Comment by herbdool** [comment]
That function is in the d7 version and it's conflicting with backdrop hook. https://git.drupalcode.org/project/rules/-/blob/7.x-2.x/rules.module

I recommend renaming this function wherever it appears in the codebase.

**Comment by Graham-72** [comment]
I think we can safely remove the function as nothing seems to make use of it. PR #80 .

**Comment by herbdool** [comment]
I agree. It was likely from when it was using Ctools to manage config.

**Comment by Graham-72** [comment]
Hopefully now fixed by PR #80 so now closing this issue.
