### ISSUE TITLE
Fix admin UI css

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/rules#48]
Some UI elements look off, including the "Show row heights" link showing off too far to the right and also the drop down items have too much space.

---
PR https://github.com/backdrop-contrib/rules/pull/53

**Comment by herbdool** [comment]
~My PR https://github.com/backdrop-contrib/rules/issues/48~

I didn't see an obvious way to reduce the padding on the data selector items. I think it may require overriding some of the right and left padding on `.ui-menu .ui-menu-item-wrapper` (which is defined in core not Rules). Can deal with that in another PR.

**Comment by herbdool** [comment]
@Graham-72 I've got a new PR. My original one was not pointing to the right branch.

**Comment by Graham-72** [comment]
@herbdool thanks.

**Comment by Graham-72** [comment]
Now acceptable with release 2.1.4? Please re-open if this is still an issue.

**Comment by herbdool** [comment]
Thanks!
