### ISSUE TITLE
Error when uninstalling.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/rules#5]
Module Rules UI uninstalls satisfactorily but when confirming the uninstall of the Rules module the site halts with the error report Error: Class name must be a valid object or a string in entity_get_controller() (line 317 of ...../core/modules/entity/entity.module).

**Comment by Graham-72** [comment]
I still get this error when uninstalling the Rules module. But it is now line 504 in entity module (BD 1.13.2).

**Comment by Graham-72** [comment]
Entity type here is reported as `rules_config`.

**Comment by Graham-72** [comment]
Rules now seems to uninstall without a problem.

**Comment by Graham-72** [comment]
Re-opening because the problem has re-appeared.

**Comment by stpaultim** [comment]
Just a quick note that I've experienced this same problem when testing the rules module.

**Comment by laryn** [comment]
I confirmed the issue still existed. It appears to be fixed after these changes: https://github.com/backdrop-contrib/rules/commit/934fa3d726fba1093871f1e49f9db408b2faa068
