### ISSUE TITLE
Call to undefined function rules_permissions_by_component()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/rules#55]
[Error reported in Ubercart's queue](https://github.com/backdrop-contrib/ubercart/issues/211) indicates that the `rules_permissions_by_component` is called but non-existent. 

It seems to be related to commits made to solve this issue (where that function was chopped out):
https://github.com/backdrop-contrib/rules/issues/5

**Comment by Graham-72** [comment]
I have undone the removal of that function and it will be back in the next release of Rules.

**Comment by Graham-72** [comment]
Now OK with release 2.1.4. Please re-open if this is still an issue.

**Comment by laryn** [comment]
@and-e-h ☝️
