### ISSUE TITLE
Call to undefined function rules_permissions_by_component() 

### ISSUE THREAD

**Issue by Helionith** [backdrop-contrib/rules#67]
Hi,
When I try to create a new component, I can't add an action and I end up with this message :
Call to undefined function rules_permissions_by_component() 
In the components overview page, I can see the component I tried to create. It looks like I can use all the links but the edit one (same message)...
If I clone it,then I can add an action. But, when I try to save the action : Call to undefined function rules_permissions_by_component().
I didn't test further.

The log returns this : 
Error : Call to undefined function rules_permissions_by_component() dans RulesPluginUI->settingsFormPermissionMatrix() (ligne 536 dans G:\wamp\www\backdropbacasable\modules\contrib\rules\ui\ui.core.inc).

The export:
{ "rules_envoyer_un_e_mail_de_rappel" : {
    "LABEL" : "Envoyer un e-mail de rappel",
    "PLUGIN" : "action set",
    "OWNER" : "rules",
    "USES VARIABLES" : { "compte" : { "label" : "compte", "type" : "user" } },
    "ACTION SET" : []
  }
}

I can create rules and they work as expected. 
Can't test the schedule thingy since I need components, 
I try to import a component from a working d7 install,  I have an error on the date format (publish/unpublish content based on a date).

Backdrop 1.15.0 - Rules 1.x-2.1.4 - PHP 7.2.10 - Not a dev.

Thanks

**Comment by laryn** [comment]
@Helionith This error was supposed to be fixed in 2.1.4 -- but you're saying it's not fixed for you and you are on that version, correct? Reference: https://github.com/backdrop-contrib/rules/issues/55

Have you cleared caches recently?

**Comment by laryn** [comment]
@Graham-72 This commit still seems to be causing problems:
https://github.com/Graham-72/rules/commit/e8a94421bdf13d66b7d645ba626a3df282f558f8

**Comment by Helionith** [comment]
Hi,
Yes, it's a fresh install, but I'm testing the different scheduler modules Backdrop provides on it. May be something went wrong somewhere...
I'm not sure, but I think I had to upgrade Rules (I used a rules.zip I downloaded b4 this install)...  
I'm going to install a new one with Rules only, and see if it's ok.

**Edit 2, few hours later :**
Nope. Same old.

Language/locale not enabled this time (just in case).
All new installed and enabled 
- Backdrop 1.15.0
- Rules 1.x-2.1.4
- Entity Plus 1.x-1.0.3
- Entity UI 1.x-1.0.0-beta
- Token Filter 1.x-1.0.1
Same error message.

The logs 

**Location |** http://bdstress/admin/config/workflow/rules/components/manage/3
**Referrer  |**  http://bdstress/admin/config/workflow/rules/components
**Message |**  Error: Call to undefined function rules_permissions_by_component() in RulesPluginUI->settingsFormPermissionMatrix() (line 536 of G:\wamp\www\bdstress\modules\rules\ui\ui.core.inc).

and (x4)

**Location |** http://bdstress/admin/config/workflow/rules/components/manage/3
**Referrer  |**  http://bdstress/admin/config/workflow/rules/components
**Message |** Notice: Undefined index: label in RulesUICategory::getOptions() (line 1231 of G:\wamp\www\bdstress\modules\rules\ui\ui.core.inc).

**Comment by Graham-72** [comment]
Apologies, my mistake, Rules 1.x-2.1.4 doesn't seem to include the fix for this. I will try and get it right with another commit.

**Comment by Helionith** [comment]
No need to apologize. Thanks for your time and your great job.

**Comment by Graham-72** [comment]
@Helionith before I make a new release of Rules please can you possibly check that this now revised version of rules.module enables you to create a new component? Thanks.

**Comment by Helionith** [comment]
It works like a charm :)
I just compared the rules.module from backdrop with the one from git... the backdrop one,misses the changes.

**Comment by Graham-72** [comment]
Yes, they will be included when I make the new release 1.x-2.1.5, soon. Thanks for testing. I will close this now.

**Comment by laryn** [comment]
Thank you @Graham-72 !

@and-e-h ☝️ FYI
