### ISSUE TITLE
Wrong conditions links on Ubercart payments methods

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/rules#7]
I'm working on Ubercart port and found that payment methods conditions links don't work because they need the components rules for payments methods which, I guess, need to be created when payment modules get installed. I see this is related to https://github.com/backdrop-contrib/rules/issues/3 and to the fact, as you say in the Readme, that rules cannot get updated from D7. Is that right?

I managed to export/import the components (which get listed even the import process triggers that error - https://github.com/backdrop-contrib/rules/issues/3) and now conditions links within ubercart payments work again, but my question is this: is there anything I need to change in Ubercart to get these rules get created on install?

Thanks

**Comment by Graham-72** [comment]
Was this fixed along with issue #21? Please re-open if necessary.
