### ISSUE TITLE
Assigning new role on creating of an account, not working

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/rules#72]
I was trying to use rules to automatically assign a new role upon the creation of an account and it's not working.

Steps to reproduce:

1. Spin up new site
2. Enable Modules
2.1 Entity Plus
2.2 Entity UI
2.3 Rules
2.4 Rules UI

3. Create new rule
3.1 Event = After saving a new user account
3.2 Action = Add user role
3.2 -- Data selector - account
3.2 -- Role - editor

4. Set configuration to allow visitors to register new accounts
4.1 http://localhost:32791/admin/config/people/settings

4. User creates a new account and logs in. 
4.1 Expectation is that new user will have the role of editor, but they don't

Is this a bug or am I missing some important step?

**Comment by ericfg** [comment]
looks like a bug to me
I thought that maybe you needed to load the entity before adding the role; nope
maybe it was permissions, so I tried making an account using an admin user; the rule is triggered but it does not save the role to the new user
wish I had better news

**Comment by stpaultim** [comment]
Thanks for confirming.

**Comment by stpaultim** [comment]
OK, I'm testing and the initial tests are good. 

I downloaded the branch with this PR and applied to my site. I am now able to assign a new role on the creation of an account. 

My next goal was to remove the role upon creation of a node. That is not working, but I am still testing and will create a new issue once I verify.

**Comment by stpaultim** [comment]
@Graham-72 - Thanks for the PR

Well, maybe I don't need to open a new ticket. My goal is to add a new role on the creation of an account and then remove that role once a user has created a node. I'm trying to limit each user to creating one node. 

With your PR the role is getting created, but it is not being removed upon creation of new node. 

I did a little experimenting and I think that the problem is with this function failing to remove the role `unset($account->roles[$role]);`

This seems related to the change you already made in `user.eval.inc`

But, it should be clear that I am a little outside my comfort zone. 

```
/**
 * Action: Remove roles from a given user.
 */
function rules_action_user_remove_role($account, $roles) {
  if ($account->uid || !empty($account->is_new)) {
    foreach ($roles as $role) {
      // If the user has this role, remove it.
      if (isset($account->roles[$role])) {
        unset($account->roles[$role]);
      }
    }
    if (!empty($account->is_new) && $account->uid) {
      // user_save() inserts roles after invoking hook_user_insert() anyway, so
      // we skip saving to avoid errors due saving them twice.
      return FALSE;
    }
  }
  else {
    return FALSE;
  }
}
```

**Comment by Graham-72** [comment]
@stpaultim thanks for trying this and explaining what you want to do. I have added to the PR so that removing a role should now work.

The issue would seem to result from a change in the keys of the array `$account->roles` from D7. I guess this is documented somewhere.

**Comment by stpaultim** [comment]
That worked perfectly. Thanks!

**Comment by stpaultim** [comment]
Thanks so much to @Graham-72 for fixing this so quickly. I see that there is already a new release containing this fix, so I'll close this issue!
