### ISSUE TITLE
Rules Scheduler warning.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/rules#74]
Here is the error message:

Warning:   require_once(......../modules/rules/rules-1.x-2.x/rules_scheduler/includes\rules_scheduler.handler.inc):  failed to open stream: No such file or directory in require_once() (line 4007 of .........../core/includes/bootstrap.inc).

Code in rules_scheduler.module has
`'RulesSchedulerDefaultTaskHandler' => 'includes\rules_scheduler.handler.inc',`
when it should have
`'RulesSchedulerDefaultTaskHandler' => 'includes/rules_scheduler.handler.inc',`

**Comment by laryn** [comment]
Looks like this was addressed in https://github.com/backdrop-contrib/rules/commit/e4408fa8daf0f4acdbda22f2947507b1dbb17964
