### ISSUE TITLE
No Data comparison for Date fields

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/rules#75]
I have difficulties to set up a Rules condition with a Data comparison on a date field: The field isn't available as Data selector.

**Steps to reproduce:**

- Create a Rule
  - React on event: After saving new content
  - Restrict by type: (your content type with a date field)
- Try to add a condition for Data comparison
  - Data to compare: (your date field)

**Behaviour:**

The date field isn't available as "Data to compare".

**Expected result:**

The field is available.

**Comment by olafgrabienski** [comment]
Some more information: I've tested other configurations and was able to select:

- *other* fields / field types of the content type (text, category, body) for a Data comparison,
- the "node created" value (which is also a date) for Data comparison,
- a *non-date* field for comparison (Data to compare), and *then* select my date field as Data value (Value to compare with), even if that doesn't make sense.

Just in case the "React on event" isn't sufficient to provide the necessary data, I've also tried to add two conditions before the Data comparison:
  - Entity is of bundle: (my content type with a date field)
  - Entity has field: (my date field)

That didn't make a difference.

When chatting about the issue in Zulip, @mazze.ch was so kind to make a test: He could easily configure the Data comparison in Drupal 7 but not in Backdrop (tried there with all date types).

We were also asking ourselves if this might be a core issue. It seems that some parts of the Date module weren't ported, see e.g. https://github.com/backdrop/backdrop-issues/issues/2766. Maybe there are other things missing in Date (only guessing).

**Comment by indigoxela** [comment]
Confirmed, no _date field_ tokens are available by default. But if I install [entity_token](https://github.com/backdrop-contrib/entity_token) the date field appears for selection.

**Comment by indigoxela** [comment]
More info: in D7 Rules has a dependency on Entity API, which ships with the Entity Token submodule.

In B1 Entity Token is a standalone module. I guess, the easiest solution is to declare a requirement for entity_token in rules module.

**Comment by olafgrabienski** [comment]
> if I install entity_token the date field appears for selection

Thanks a lot for finding this out, @indigoxela! After installing Entity Token, I was also able to select a date field for Data comparison.

> I guess, the easiest solution is to declare a requirement for entity_token in rules module.

Unfortunately, Entity Token isn't stable, currently there are two important [open issues](https://github.com/backdrop-contrib/entity_token/issues). I'd suggest to not declare it a requirement at this time.

---

~~Finally, sort of off-topic but maybe related: With Entity Token, I'm yes able to select a Date field but I see now that I'm (still) not able to select a Reference field. (Using [Reference](https://github.com/backdrop-contrib/reference) module on the site in question which isn't in an ideal state.)~~ **Edit:** Testing with [References](https://github.com/backdrop-contrib/references) I had no problem to select a Node Reference field for Data comparison.

**Comment by indigoxela** [comment]
> Unfortunately, Entity Token isn't stable

Porting this module seems to have happened recently. Let's give @docwilmot some time to fix the issues.

**Comment by laryn** [comment]
Note: There is discussion of moving the date bits out of Entity Token and into Entity Plus (where they probably belong):

 - https://github.com/backdrop-contrib/entity_plus/issues/33

Closing this issue as it is being fixed in Entity Plus (from what I understand). Please reopen or make a new issue if there's something else that needs attention.
