### ISSUE TITLE
entity_build_content() is duplicated in Entity Metadata Wrapper and Rules

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/rules#8]
Also, I noted that many of the functions in `entity.functions.inc` are not called anywhere else in Rules, and the few which do have core alternatives. We should get rid of this file.

`entity.features.inc` should also go since Backdrop doesnt really support features (CMI built-in).

**Comment by robertgarrigos** [comment]
I'm having a lot of problems with ubercart because of this two commits. These are the errors:
#9, #10 and #13

I wonder if it would be easier to have these two files back and just delete the duplicated functions.

**Comment by robertgarrigos** [comment]
For the moment I solve this by adding back those two files and deleting entity_load_multiple_by_name() and entity_build_content() functions which are already declared in entity metadata wrapper.

entity.features.inc is needed for the EntityDefaultFeaturesController class, extended by a class in rules.features.inc
