### ISSUE TITLE
Missing data selection for Email fields

### ISSUE THREAD

**Issue by allsite** [backdrop-contrib/rules#85]
While adding a user account entity via Rules, "Email" field formatters are not available for selection for populating the newly created account email. "Text" fields are available, but not "Email" fields.

**Comment by argiepiano** [comment]
@allsite , would you please add a bit more information about this issue, such as the steps needed to reproduce the problem?

**Comment by argiepiano** [comment]
I'm unable to reproduce this issue. 

1. I created a test rule that reacts to content being created
2. I added the action "Create new entity" and selected User
3. The email field is shown there
4. I can switch to "Data selection" widget without any issue
5. The rule works as expected.

My guess is that this got fixed along the way. If you can provide specific steps to reproduce, feel free to reopen.

<img width="894" alt="Screen Shot 2022-05-28 at 10 51 16 AM" src="https://user-images.githubusercontent.com/9938978/170835134-d009d9cc-af3d-4193-a6ef-0dca3b6768e4.png">
<img width="1192" alt="Screen Shot 2022-05-28 at 10 52 55 AM" src="https://user-images.githubusercontent.com/9938978/170835136-84296e7e-3ee4-48be-b85a-7a129027b9e3.png">
