### ISSUE TITLE
missing entity_defaults_rebuild() function

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/rules#9]
Porting ubercart I had to include entity_flush_caches() function, named as uc_entity_flush_caches(), which calls entity_defaults_rebuild(). This is missing. @docwilmot said it would be added to rules, so this is just a reminder ;-)

**Comment by herbdool** [comment]
I'm not sure if the core function entity_info_cache_clear() is a good replacement or not.

Alternatively these functions should either be added to core or they should go in centralized module like entity_meta_wrapper

**Comment by Graham-72** [comment]
I'm thinking this is no longer an issue. Please re-open if necessary.
