### ISSUE TITLE
Functional Tests

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/rules#92]
I've added GHA for functional tests on PRs, and the tests will need some work before they are green. Ideally I'd like to see the tests passing before the next release as a measure of reliability on the merges and fixes that I have added and those pulled from D7.

**Comment by laryn** [comment]
- [ ] Rules Core Integration | Rules Core Integration | Tests provided integration for Backdrop core.
 _65 passes, 7 fails, 9 exceptions, and 3 debug messages._
 - [x] Rules Data tests | Rules Data tests | Tests rules data saving and type matching. 
 _The test run did not successfully finish._ 
 - [x] Rules Engine tests | Rules Engine tests | Test using the rules API to create and evaluate rules. 
 _99 passes, 7 fails, and 8 exceptions._
 - [x] Rules I18n | Rules I18n | Tests translating Rules configs.
  _The test run did not successfully finish._ See also https://github.com/backdrop-contrib/entity_plus/issues/67
 - [x] Reaction Rules | Tests triggering reactive rules.  _1 exception_
 - [x] Rules event dispatchers | Rules event dispatchers | Tests event dispatcher functionality.
 - [x] Rules invocation enabled | Rules invocation enabled | Tests that Rules events are enabled during menu item loads.
 - [x] Rules Scheduler tests | Rules Scheduler tests | Test scheduling components.
 - [x] Rules UI Minimal Profile Tests | Rules UI Minimal Profile Tests | Tests UI support for minimal profile.
 - [x] Rules UI Tests | Rules UI Tests | Tests Rules UI.

**Comment by laryn** [comment]
From @bugfolder in another thread:

> I do observe that the same functional tests are failing for Rules and UC related to `file_exists()`, etc., which suggests that the problem lies on in these modules but in the testing configuration.

**Comment by bugfolder** [comment]
Locally run tests fail, too, so contra my previous comment, some of the issues must be in Rules.

**Comment by bugfolder** [comment]
I set up a separate issue https://github.com/backdrop-contrib/rules/issues/114 to get the remaining Rules tests working from the UI. Will leave this issue to address getting them running under GHA (when they're ready).

**Comment by bugfolder** [comment]
With outstanding recent work from @argiepiano and updating the GHA, all Rules tests are now passing in GHA (and locally) 🎉🎉🎉, so closing this issue.

**Comment by laryn** [comment]
I’ll add a few 🎉🎊🎉🎊🎉🎊
